# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: book.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbook.proto\x12\x04\x62ook\"&\n\x13SimpleStringMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\"\'\n\x0b\x42ookRequest\x12\x18\n\x04\x62ook\x18\x01 \x01(\x0b\x32\n.book.Book\"U\n\x0c\x42ookResponse\x12\x18\n\x04\x62ook\x18\x01 \x01(\x0b\x32\n.book.Book\x12\x15\n\rresponse_code\x18\x02 \x01(\t\x12\x14\n\x0cresponse_msg\x18\x03 \x01(\t\"W\n\rBooksResponse\x12\x19\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\n.book.Book\x12\x15\n\rresponse_code\x18\x02 \x01(\t\x12\x14\n\x0cresponse_msg\x18\x03 \x01(\t\"\xab\x01\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1f\n\x05genre\x18\x03 \x01(\x0e\x32\x10.book.Book.Genre\x12\x0c\n\x04tags\x18\x04 \x03(\t\x12\x1c\n\x06\x61uthor\x18\x05 \x01(\x0b\x32\x0c.book.Author\"<\n\x05Genre\x12\n\n\x06UNKOWN\x10\x00\x12\r\n\tDETECTIVE\x10\x01\x12\x0b\n\x07MYSTERY\x10\x02\x12\x0b\n\x07ROMANCE\x10\x03\"/\n\x06\x41uthor\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x64ob\x18\x03 \x01(\t2\x8d\x03\n\x0b\x42ookService\x12>\n\x12GetBooksByBookName\x12\x11.book.BookRequest\x1a\x13.book.BooksResponse\"\x00\x12\x36\n\x0bGetBookById\x12\x11.book.BookRequest\x1a\x12.book.BookResponse\"\x00\x12\x42\n\x08GetHello\x12\x19.book.SimpleStringMessage\x1a\x19.book.SimpleStringMessage\"\x00\x12\x42\n\x0eGetAllContents\x12\x11.book.BookRequest\x1a\x19.book.SimpleStringMessage\"\x00\x30\x01\x12J\n\x0eSetAllContents\x12\x19.book.SimpleStringMessage\x1a\x19.book.SimpleStringMessage\"\x00(\x01\x12\x32\n\x12StreamAllBooksById\x12\n.book.Book\x1a\n.book.Book\"\x00(\x01\x30\x01\x42*\n\x1d\x63om.example.client.rpcserviceB\tBookProtob\x06proto3')



_SIMPLESTRINGMESSAGE = DESCRIPTOR.message_types_by_name['SimpleStringMessage']
_BOOKREQUEST = DESCRIPTOR.message_types_by_name['BookRequest']
_BOOKRESPONSE = DESCRIPTOR.message_types_by_name['BookResponse']
_BOOKSRESPONSE = DESCRIPTOR.message_types_by_name['BooksResponse']
_BOOK = DESCRIPTOR.message_types_by_name['Book']
_AUTHOR = DESCRIPTOR.message_types_by_name['Author']
_BOOK_GENRE = _BOOK.enum_types_by_name['Genre']
SimpleStringMessage = _reflection.GeneratedProtocolMessageType('SimpleStringMessage', (_message.Message,), {
  'DESCRIPTOR' : _SIMPLESTRINGMESSAGE,
  '__module__' : 'book_pb2'
  # @@protoc_insertion_point(class_scope:book.SimpleStringMessage)
  })
_sym_db.RegisterMessage(SimpleStringMessage)

BookRequest = _reflection.GeneratedProtocolMessageType('BookRequest', (_message.Message,), {
  'DESCRIPTOR' : _BOOKREQUEST,
  '__module__' : 'book_pb2'
  # @@protoc_insertion_point(class_scope:book.BookRequest)
  })
_sym_db.RegisterMessage(BookRequest)

BookResponse = _reflection.GeneratedProtocolMessageType('BookResponse', (_message.Message,), {
  'DESCRIPTOR' : _BOOKRESPONSE,
  '__module__' : 'book_pb2'
  # @@protoc_insertion_point(class_scope:book.BookResponse)
  })
_sym_db.RegisterMessage(BookResponse)

BooksResponse = _reflection.GeneratedProtocolMessageType('BooksResponse', (_message.Message,), {
  'DESCRIPTOR' : _BOOKSRESPONSE,
  '__module__' : 'book_pb2'
  # @@protoc_insertion_point(class_scope:book.BooksResponse)
  })
_sym_db.RegisterMessage(BooksResponse)

Book = _reflection.GeneratedProtocolMessageType('Book', (_message.Message,), {
  'DESCRIPTOR' : _BOOK,
  '__module__' : 'book_pb2'
  # @@protoc_insertion_point(class_scope:book.Book)
  })
_sym_db.RegisterMessage(Book)

Author = _reflection.GeneratedProtocolMessageType('Author', (_message.Message,), {
  'DESCRIPTOR' : _AUTHOR,
  '__module__' : 'book_pb2'
  # @@protoc_insertion_point(class_scope:book.Author)
  })
_sym_db.RegisterMessage(Author)

_BOOKSERVICE = DESCRIPTOR.services_by_name['BookService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\035com.example.client.rpcserviceB\tBookProto'
  _SIMPLESTRINGMESSAGE._serialized_start=20
  _SIMPLESTRINGMESSAGE._serialized_end=58
  _BOOKREQUEST._serialized_start=60
  _BOOKREQUEST._serialized_end=99
  _BOOKRESPONSE._serialized_start=101
  _BOOKRESPONSE._serialized_end=186
  _BOOKSRESPONSE._serialized_start=188
  _BOOKSRESPONSE._serialized_end=275
  _BOOK._serialized_start=278
  _BOOK._serialized_end=449
  _BOOK_GENRE._serialized_start=389
  _BOOK_GENRE._serialized_end=449
  _AUTHOR._serialized_start=451
  _AUTHOR._serialized_end=498
  _BOOKSERVICE._serialized_start=501
  _BOOKSERVICE._serialized_end=898
# @@protoc_insertion_point(module_scope)
